import React, { useState } from 'react';

interface SettingsProps {
    onBack?: () => void;
}

const Settings: React.FC<SettingsProps> = ({ onBack }) => {
    const [showSeedMode, setShowSeedMode] = useState<boolean>(false);
    const [showPrivateKey, setShowPrivateKey] = useState<boolean>(false);

    // Mock seed phrase
    const seedWords = ["apple", "butter", "crush", "drift", "eagle", "fossil", "guitar", "hover", "iron", "jungle", "karma", "lemon"];

    // Mock private key
    const privateKey = "0x8f2a...e3b4"; // just a mock

    return (
        <div className="max-w-4xl mx-auto px-4 py-8 animate-fadeIn">
            <div className="flex items-center gap-4 mb-8">
                {onBack && (
                    <button
                        onClick={onBack}
                        className="w-10 h-10 flex items-center justify-center rounded-full bg-white border border-gray-200 text-gray-500 hover:text-black hover:border-black hover:shadow-sm transition-all"
                        title="Back to Portfolio"
                    >
                        <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M10 19l-7-7m0 0l7-7m-7 7h18" /></svg>
                    </button>
                )}
                <h1 className="text-3xl font-black text-black tracking-tight">Account Settings</h1>
            </div>

            <div className="space-y-8">
                {/* Connected Accounts Session */}
                <section className="bg-white border border-gray-100 rounded-3xl p-6 shadow-sm">
                    <h2 className="text-lg font-bold text-black mb-1">Connected Accounts</h2>
                    <p className="text-xs font-medium text-gray-500 mb-6">Manage how you sign in to Loka.</p>

                    <div className="space-y-4">
                        <div className="flex items-center justify-between p-4 bg-gray-50 rounded-2xl border border-gray-100">
                            <div className="flex items-center gap-4">
                                <div className="w-10 h-10 bg-white shadow-sm border border-gray-100 rounded-xl flex items-center justify-center font-bold text-black">
                                    G
                                </div>
                                <div className="flex flex-col">
                                    <span className="text-sm font-bold text-black">Google</span>
                                    <span className="text-xs text-green-600 font-bold bg-green-50 px-2 py-0.5 rounded-full inline-block mt-1 w-fit">hello@moltcash.com</span>
                                </div>
                            </div>
                        </div>

                        <div className="flex items-center justify-between p-4 bg-gray-50 rounded-2xl border border-gray-100">
                            <div className="flex items-center gap-4">
                                <div className="w-10 h-10 bg-white shadow-sm border border-gray-100 rounded-xl flex items-center justify-center font-serif text-lg text-black">
                                    𝕏
                                </div>
                                <div className="flex flex-col">
                                    <span className="text-sm font-bold text-black">X (Twitter)</span>
                                    <span className="text-xs text-green-600 font-bold bg-green-50 px-2 py-0.5 rounded-full inline-block mt-1 w-fit">@moltcash</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                {/* Wallet Security Session */}
                <section className="bg-white border border-gray-100 rounded-3xl p-6 shadow-sm">
                    <h2 className="text-lg font-bold text-red-500 mb-1">Wallet Security</h2>
                    <p className="text-xs font-medium text-gray-500 mb-6">Your wallet is non-custodial and generated by the platform. You must back up your seed phrase. Never share these with anyone.</p>

                    <div className="space-y-6">
                        {/* Seed Phrase */}
                        <div>
                            <div className="flex items-center justify-between mb-3">
                                <h3 className="text-sm font-bold text-black w-1/3">Secret Recovery Phrase</h3>
                                {!showSeedMode ? (
                                    <button
                                        onClick={() => setShowSeedMode(true)}
                                        className="text-xs font-bold text-black border border-gray-200 bg-white hover:bg-gray-50 px-4 py-2 rounded-xl transition-colors shadow-sm"
                                    >
                                        Reveal Phrase
                                    </button>
                                ) : (
                                    <div className="flex gap-2">
                                        <button
                                            onClick={() => {
                                                navigator.clipboard.writeText(seedWords.join(' '));
                                                // Optional: add a small toast indication here
                                            }}
                                            className="text-xs font-bold text-black border border-gray-200 bg-white hover:bg-gray-50 px-4 py-2 rounded-xl transition-colors shadow-sm flex items-center gap-2"
                                        >
                                            <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" /></svg>
                                            Copy
                                        </button>
                                        <button
                                            onClick={() => setShowSeedMode(false)}
                                            className="text-xs font-bold text-gray-400 border border-transparent hover:bg-gray-50 px-4 py-2 rounded-xl transition-colors"
                                        >
                                            Hide
                                        </button>
                                    </div>
                                )}
                            </div>

                            {showSeedMode ? (
                                <div className="grid grid-cols-3 md:grid-cols-4 gap-3 bg-gray-50 p-4 rounded-2xl border border-gray-100 animate-fadeIn">
                                    {seedWords.map((word, i) => (
                                        <div key={i} className="flex bg-white border border-gray-200 rounded-lg px-3 py-2 items-center shadow-sm">
                                            <span className="text-[10px] text-gray-400 font-bold w-5">{i + 1}.</span>
                                            <span className="text-sm font-black text-black ml-1">{word}</span>
                                        </div>
                                    ))}
                                </div>
                            ) : (
                                <div className="bg-gray-50 p-6 rounded-2xl border border-gray-100 border-dashed flex items-center justify-center">
                                    <p className="text-xs font-bold tracking-widest  text-gray-400 text-center">Hidden for security <br /> Click reveal to view</p>
                                </div>
                            )}
                        </div>

                        <hr className="border-gray-100" />

                        {/* Private Key */}
                        {/*<div>
                            <div className="flex items-center justify-between mb-3">
                                <h3 className="text-sm font-bold text-black w-1/3">Private Key</h3>
                                <button 
                                    onClick={() => setShowPrivateKey(!showPrivateKey)}
                                    className="text-xs font-bold text-black border border-gray-200 bg-white hover:bg-gray-50 px-4 py-2 rounded-xl transition-colors shadow-sm"
                                >
                                    {showPrivateKey ? 'Hide Key' : 'Reveal Key'}
                                </button>
                            </div>
                            {showPrivateKey && (
                                <div className="bg-gray-50 p-4 rounded-2xl border border-gray-100 flex items-center justify-between animate-fadeIn">
                                    <code className="text-sm font-bold text-black font-mono break-all pr-4">0x4a01f9...e1b5c49d8e</code>
                                </div>
                            )}
                        </div>*/}

                    </div>
                </section>
            </div>

        </div>
    );
};

export default Settings;
