
import React from 'react';

interface RiskModalProps {
  onAccept: () => void;
  onClose?: () => void;
}

const RiskModal: React.FC<RiskModalProps> = ({ onAccept, onClose }) => {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-white/60 backdrop-blur-xl p-4">
      <div className="max-w-md w-full bg-white rounded-[40px] p-10 border border-gray-100 shadow-2xl relative">
        {/* Close Button for manual access */}
        {onClose && (
          <button
            onClick={onClose}
            className="absolute top-8 right-8 text-gray-300 hover:text-black transition-colors"
          >
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        )}

        <h2 className="font-serif text-4xl italic mb-6 text-black">Disclaimer.</h2>
        <div className="space-y-6 text-gray-500 text-sm leading-relaxed mb-10">
          <p>
            <span className="text-black font-bold  tracking-widest text-[10px] block mb-1">1. Non-Yield Bearing</span>
            AIUSD is a high-liquidity payment instrument, not a savings product. It does not generate interest for users.
          </p>
          <p>
            <span className="text-black font-bold  tracking-widest text-[10px] block mb-1">2. Treasury Revenue</span>
            All yields generated by underlying US Treasuries are 100% captured by the LOKA Protocol for stability and infrastructure costs.
          </p>
          <p>
            <span className="text-black font-bold  tracking-widest text-[10px] block mb-1">3. Redemption Policy</span>
            Small redemptions are processed T+0. Large redemptions may be subject to a <span className="text-black font-bold">T+7 settlement window</span> to protect treasury positions.
          </p>
        </div>
        <button
          onClick={onAccept}
          className="w-full py-5 bg-black text-white rounded-full font-bold  text-[11px] tracking-[0.3em] hover:bg-gray-800 transition-all shadow-lg"
        >
          Agree & Continue
        </button>
      </div>
    </div>
  );
};

export default RiskModal;
